Fixed init scipt

diff --git a/fplot_init b/fplot_init
--- a/fplot_init
+++ b/fplot_init
@@ -1,47 +1,103 @@
 #!/usr/bin/env bash
 # shellcheck disable=2034
 #---------------------------------------------------------------------
-# Fplot init file
+# Fplot init script
 #
 #---------------------------------------------------------------------
 #
 
-##V Directory where script is located
-BP_SELF_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 
 #---------------------------------------------------------------------
+
 InitSettings() {
-    MODULE="${BP_SELF_DIR}/${BP_SELF}"
-}
-
-bpModuleIsInstalled() {
-    if [ -e "${BP_CONFIG_MODULES}/"$(basename "$1") ]; then
-        return 0
-    else
-        return 1
-    fi
+  MODULE="${BP_SELF_DIR}/${BP_SELF_NAME}"
 }
 
 direct_exec() {
-    # echo "$MODULE"
-    echo "${BP_CONFIG_MODULES}/$(basename "$MODULE")"
-
-    if bpModuleIsInstalled "$MODULE"; then
-        if bpReadBoolDY "Do you want to remove init module?"; then
-            # bpRmModule "${MODULE}"
-            bpRmModule "$(basename ${MODULE})"
-        fi
-    else
-        if bpReadBoolDY "Do you want to install init module?"; then
-            bpAddModule "${MODULE}"
-        fi
+  if bpModuleIsInstalled "$MODULE"; then
+    if [ -n "$BP_QUIET" ] || bpReadBoolDY "Do you want to remove init module?"; then
+      bpRmModule "$(basename ${MODULE})"
     fi
+  else
+    if [ -n "$BP_QUIET" ] || bpReadBoolDY "Do you want to install init module?"; then
+      bpAddModule "${MODULE}"
+    fi
+  fi
 }
 
 source_exec() {
-    # Add script path to global path
-    export PATH=${PATH}:${BP_SELF_DIR}
+  bpLoadSettings
+
+  # Add script path to global path
+  export PATH=${PATH}:${BP_SELF_DIR}
+
+  # Add variable pointing to bashplate dir
+  export BP_PATH=${BP_SELF_DIR}
+
+  # Development mode
+  if [ -f "${BP_SELF_DIR}/DEV" ]; then
+    export PATH=${PATH}:${BP_SELF_DIR}/dev
+    alias cdb='cd "${BP_SELF_DIR}"'
+  fi
+
+  # Indicated that initscript was run
+  export BP_INIT_RUN=1
+
 }
+
+bpSettingsDir=~/.config/bashplates
+bpSettings=${bpSettingsDir}/bashplates.conf
+
+addSetting() {
+  echo "# "${3} >>${bpSettings}
+  echo ${1}"=\""${2}"\"" >>${bpSettings}
+  echo >>${bpSettings}
+}
+
+createSettings() {
+
+  echo "Creating new bashplates settings file. ${bpSettings}"
+  mkdir -p ${bpSettingsDir}
+
+  echo "# " >>${bpSettings}
+  echo "# Bashplates common settings" >${bpSettings}
+  echo "# " >>${bpSettings}
+  echo >>${bpSettings}
+
+  addSetting "BP_NAME" "John Doe" "Name of user"
+  addSetting "BP_EMAIL" "JohnDoe@foo.bar" "Email of user"
+  addSetting "BP_EDITOR" "vi" "Default editor"
+  addSetting "BP_LICENSE" "MIT" "Default project license"
+  addSetting "BP_ORG" "ACME" "Default organisation"
+  addSetting "BP_DIFF" "meld" "Default diff program"
+}
+
+bpLoadSettings() {
+  if [ -n "${bpSettings}" ]; then
+    if [ -e ${bpSettings} ]; then
+      source ${bpSettings}
+    else
+      createSettings
+      source ${bpSettings}
+    fi
+  fi
+	
+  export BP_NAME
+  export BP_EMAIL
+  export BP_EDITOR
+  export BP_LICENSE
+  export BP_ORG
+  export BP_PATH
+}
+
+_bp_completions() {
+  COMPREPLY=$(bp help)
+}
+
+_bpdev_completions() {
+  COMPREPLY=$(bpdev completion)
+}
+
 
 #---------------------------------------------------------------------
 
@@ -100,7 +156,7 @@ BP_C_CRITICAL="${E_BG_RED}${E_WHITE}"
 # ret colorized string
 #
 bpColorizeFile() { ##I Colorize string containing filename
-    echo "${BP_C_PATH}$(dirname "$1")/${BP_C_FILENAME}$(basename "$1")${E_RESET}"
+  echo "${BP_C_PATH}$(dirname "$1")/${BP_C_FILENAME}$(basename "$1")${E_RESET}"
 }
 
 #
@@ -110,16 +166,16 @@ bpColorizeFile() { ##I Colorize string containing filename
 #
 bpReadStr() { ##I Read string from commandline
 
-    if [ "${2}" == "" ]; then
-        read -erp "${1} > " result
-    else
-        read -erp "${1} [$2] > " result
-        if [ "${result}" == "" ]; then
-            result="${2}"
-        fi
+  if [ "${2}" == "" ]; then
+    read -erp "${1} > " result
+  else
+    read -erp "${1} [$2] > " result
+    if [ "${result}" == "" ]; then
+      result="${2}"
     fi
+  fi
 
-    echo "${result}"
+  echo "${result}"
 }
 
 #
@@ -130,23 +186,23 @@ bpReadStr() { ##I Read string from commandline
 # return integer read from cmdline/default if enter pressed
 #
 bpReadInt() { ##I Read integer from commandline
-    while true; do
-        if [ "${2}" == "" ]; then
-            read -erp "${1} ($3-$4) >" result
-            if [ "${result}" == "" ]; then
-                result=$(($3 - 1))
-            fi
-        else
-            read -erp "${1} ($3-$4) [$2] >" result
-            if [ "${result}" == "" ]; then
-                result="${2}"
-            fi
-        fi
-        if [ $((result)) -ge "$3" ] && [ $((result)) -le "$4" ]; then
-            break
-        fi
-    done
-    echo "${result}"
+  while true; do
+    if [ "${2}" == "" ]; then
+      read -erp "${1} ($3-$4) >" result
+      if [ "${result}" == "" ]; then
+        result=$(($3 - 1))
+      fi
+    else
+      read -erp "${1} ($3-$4) [$2] >" result
+      if [ "${result}" == "" ]; then
+        result="${2}"
+      fi
+    fi
+    if [ $((result)) -ge "$3" ] && [ $((result)) -le "$4" ]; then
+      break
+    fi
+  done
+  echo "${result}"
 }
 
 #
@@ -155,27 +211,27 @@ bpReadInt() { ##I Read integer from commandline
 # return 0 = Yes, 1=No
 #
 bpReadBool() { ##I Ask yes/no question generic
-    while true; do
+  while true; do
 
-        if [ "$2" -eq 1 ]; then
-            yn=$(bpReadStr "${1} [y/N]")
-        else
-            yn=$(bpReadStr "${1} [Y/n]")
-        fi
+    if [ "$2" -eq 1 ]; then
+      yn=$(bpReadStr "${1} [y/N]")
+    else
+      yn=$(bpReadStr "${1} [Y/n]")
+    fi
 
-        case "$yn" in
-        [Yy]*)
-            return 0
-            ;;
-        [Nn]*)
-            return 1
-            ;;
-        "")
-            return "$2"
-            ;;
-        *) echo "Please answer yes or no." ;;
-        esac
-    done
+    case "$yn" in
+    [Yy]*)
+      return 0
+      ;;
+    [Nn]*)
+      return 1
+      ;;
+    "")
+      return "$2"
+      ;;
+    *) echo "Please answer yes or no." ;;
+    esac
+  done
 }
 
 #
@@ -183,8 +239,8 @@ bpReadBool() { ##I Ask yes/no question generic
 # return 0 = Yes, 1=No
 #
 bpReadBoolDY() { ##I Ask yes/no question default yes
-    bpReadBool "$1" 0
-    return $?
+  bpReadBool "$1" 0
+  return $?
 }
 
 #
@@ -192,28 +248,28 @@ bpReadBoolDY() { ##I Ask yes/no question default yes
 # return 0 = Yes, 1=No
 #
 bpReadBoolDN() { ##I Ask yes/no question default no
-    bpReadBool "$1" 1
-    return $?
+  bpReadBool "$1" 1
+  return $?
 }
 
 bpOk() { ##I Success message
-    echo -e "[${BP_C_OK}Ok${E_RESET}] $1"
+  echo -e "[${BP_C_OK}Ok${E_RESET}] $1"
 }
 
 bpInfo() { ##I Info message
-    echo -e "[${BP_C_INFO}Info${E_RESET}] $1"
+  echo -e "[${BP_C_INFO}Info${E_RESET}] $1"
 }
 
 bpDebug() { ##I Debug message
-    echo -e "[${BP_C_DEBUG}Dbg${E_RESET}] $1"
+  echo -e "[${BP_C_DEBUG}Dbg${E_RESET}] $1"
 }
 
 bpWarning() { ##I Warning message
-    echo -e "[${BP_C_WARNING}Warning${E_RESET}] $1"
+  echo -e "[${BP_C_WARNING}Warning${E_RESET}] $1"
 }
 
 bpError() { ##I Error message
-    echo -e "[${BP_C_ERROR}Error${E_RESET}] $1"
+  echo -e "[${BP_C_ERROR}Error${E_RESET}] $1"
 }
 
 #
@@ -221,48 +277,59 @@ bpError() { ##I Error message
 # $2 link
 #
 bpLn() { ##I Create symbolic link
-    if [ ! -L "$1" ]; then
-        if ln -sf "${1}" "${2}"; then
-            bpOk "Creating link $(bpColorizeFile "${2}")."
-            return 0
-        else
-            bpError "Failed to create link $(bpColorizeFile "${2}")."
-            return 1
-        fi
+  if [ ! -L "$1" ]; then
+    if ln -sf "${1}" "${2}"; then
+      bpOk "Creating link $(bpColorizeFile "${2}")."
+      return 0
+    else
+      bpError "Failed to create link $(bpColorizeFile "${2}")."
+      return 1
     fi
+  fi
 }
 
 #
 # $1 file(s) to be removed
 #
 bpRm() { ##I Remove file(s)
-    if rm -rf "${1}"; then
-        bpOk "Removing file $(bpColorizeFile "${1}")."
-        return 0
-    else
-        bpError "Failed removing file $(bpColorizeFile "${1}")."
-        return 1
-    fi
+  if rm -rf "${1}"; then
+    bpOk "Removing file $(bpColorizeFile "${1}")."
+    return 0
+  else
+    bpError "Failed removing file $(bpColorizeFile "${1}")."
+    return 1
+  fi
+}
+
+bpModuleIsInstalled() {
+  if [ -e "${BP_CONFIG_MODULES}/"$(basename "$1") ]; then
+    return 0
+  else
+    return 1
+  fi
 }
 
 bpAddModule() { ##I Add init script to
-    m=$(realpath "${1}")
-    if [ ! -L "$m" ]; then
-        rm -f "${BP_CONFIG_MODULES}/$(basename "${m}")"
-        bpLn "$m" "${BP_CONFIG_MODULES}/."
-    fi
+  m=$(realpath "${1}")
+  if [ ! -L "$m" ]; then
+    rm -f "${BP_CONFIG_MODULES}/$(basename "${m}")"
+    bpLn "$m" "${BP_CONFIG_MODULES}/."
+  fi
 }
 
 bpRmModule() { ##I Remove module
-    bpRm "${BP_CONFIG_MODULES}/${1}"
+  bpRm "${BP_CONFIG_MODULES}/${1}"
 }
 
 #---------------------------------------------------------------------
 # Internal variables
 #---------------------------------------------------------------------
 
+# Directory where script is located
+BP_SELF_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
+
 ##V Name of script
-BP_SELF=$(basename "$0")
+BP_SELF_NAME=fplot_init
 
 ##V Settings directory
 BP_CONFIG_DIR=~/.config/bashplates
@@ -272,8 +339,15 @@ BP_CONFIG_MODULES="${BP_CONFIG_DIR}/modules"
 
 InitSettings
 
-if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
-    direct_exec
-else
-    source_exec
+getopts ":q" option
+if [ "$option" == "q" ]; then
+  BP_QUIET=1
 fi
+
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  BP_SELF_NAME=$(basename "$0")
+	direct_exec
+else
+  source_exec
+fi
+
